STEP1_PATH = ""
STEP2_PATH = ""
STEP3_PATH = ""

run-all:
	pipenv run python command.py

run-step1:
	pipenv run python lda --step_id=1 --path STEP1_PATH

run-step2:
	pipenv run python lda --step_id=2 --path STEP2_PATH

run-step3:
	pipenv run python lda --step_id=3 --path STEP3_PATH